feat: 입력값에 문제가 있는 경우 에러 출력 기능 추가
happyeveryone96/form-practice pull request #1
Opened 2023-02-24 14:57 UTC by happyeveryone96

- 중첩 함수 개념을 활용해 최소 글자 수를 검증하는 min 함수와 최대 글자 수를 검증하는 max 함수 구현 (utils/validate.ts)
- min 함수와 max 함수를 활용해 조건을 만족하지 않는 경우 메세지를 return하는 checkValidate 함수 구현 (utils/validate.ts)
- TextFiled 컴포넌트에서 checkValidate 함수를 활용해 에러를 조건부 렌더링

2023-02-25 04:01 UTC, morishjs requested changes

2023-02-25 04:01 UTC, morishjs commented on src/hooks/useInput.tsx
> +  const maxPasswordValidate = maxValidate(password);
`useInput`은 TextField 에 source, validate가 뭐가 들어오든지 상관없도록 변경해주실 수 있을까요?

구체적으로 설명드리자면 요구사항이 변경돼서 `name` 이 아니라 `nickname` 으로 source가 변경된다면
`const {name , password} = values;` 에러가 발생될 것입니다. 마찬가지로 props.validate도 지금은 `min(5), max(10)` 밖에 없지만 추후에 또 다른 검증하는 함수들이 생성되면 `minValidate`, `maxValidate`이 아닌 다른 함수들이 이곳에 생성됩니다. 좀 더 극단적으로는 min, max 같은 검증 함수가 아니라 1000개의 검증 함수가 있다면 이 코드가 길어질 것 같네요.

이런 걸 Open-closed principle 라고 하는데 관심있으면 한번 검색해보세요!

2023-02-25 07:42 UTC, happyeveryone96 commented on src/hooks/useInput.tsx
> +  const maxPasswordValidate = maxValidate(password);
네 수정해보겠습니다!

2023-03-02 02:37 UTC, morishjs requested changes

2023-03-02 02:37 UTC, morishjs commented on src/hooks/useInput.tsx
> +      const [err] = errs.filter((e) => e !== undefined);
error의 타입을 string 보다는 array로 해서 넘겨주면 더 좋을 것 같네요. 이 부분은 오늘 라이브 세션에서 한번 해보시죠

2023-03-02 02:37 UTC, morishjs commented on src/components/TextField.tsx
> +        <div>{source === "name" && errors.name}</div>
```jsx
<div>errors[source]</div>
```

 이렇게 하면 TextField는 더 이상 "name", "password"에 의존적이지 않게 됩니다.

2023-03-02 02:39 UTC, morishjs requested changes

2023-03-02 02:39 UTC, morishjs commented on src/utils/validate.ts
> +  for (let key in obj) {
```javascript
return Object.values(obj).some(value => value !== undefined)
```
이렇게 하는 것이 더 간단하겠네요

2023-03-02 02:39 UTC, morishjs commented on src/utils/validate.ts
> +const isError = (obj: Record<string, any>) => {
obj 에 에러가 있는지 체크하는거니까 `isError` 보다는 `hasError`가 더 적절해보입니다

2023-03-02 03:49 UTC, happyeveryone96 commented on src/hooks/useInput.tsx
> +      const [err] = errs.filter((e) => e !== undefined);
네!

2023-03-02 03:49 UTC, happyeveryone96 commented on src/components/TextField.tsx
> +        <div>{source === "name" && errors.name}</div>
수정해보겠습니다!

2023-03-02 03:50 UTC, happyeveryone96 commented on src/utils/validate.ts
> +  for (let key in obj) {
넵 수정해볼게요!

2023-03-02 03:51 UTC, happyeveryone96 commented on src/utils/validate.ts
> +const isError = (obj: Record<string, any>) => {
수정해보겠습니다

2023-03-02 11:33 UTC, morishjs approved these changes

2023-03-02 11:33 UTC, merged